In [3]:
'''
Created on 18 d'octubre de 2021
@author: lbn
'''
a = "Curs Python"
'''exercici 3: Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.
'''
#primer una funció que ens dona una matriu de NxM
import numpy as np
import random
n = int(input("Indica el número de files: \n"))
m = int(input("Indica el número de columnes: \n"))
matriu = np.random.randint(0, 100, size=(n, m))
print(matriu)

Indica el número de files: 
5
Indica el número de columnes: 
3
[[ 2 10 36]
 [37 77 41]
 [69 72 18]
 [55  0 47]
 [43 27 56]]


In [4]:
#segon, la suma de les files i de les columnes, de la matriu creada NxM
sumafilas = np.sum(matriu, axis=1)
sumacolumnes = np.sum(matriu, axis=0)
print(sumafilas)
print(sumacolumnes)


[ 48 155 159 102 126]
[206 186 198]
