In [6]:
'''
Created on 18 d'octubre de 2021
@author: lbn
'''
a = "Curs Python"
'''exercici 2: Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.'''
'''PER ACONSEGUIR UNA MATRIU NxM AMB NÚMEROS ALEATORIS DE 0 A 100'''
import numpy as np
import random
n = int(input("Indica el número de files: \n"))
m = int(input("Indica el número de columnes: \n"))
matriu = np.random.randint(0, 100, size=(n, m))
print(matriu)


Indica el número de files: 
10
Indica el número de columnes: 
10
[[64 92 37 87 25 74  8 19 14 79]
 [92 27 22  4 26 50 87 88 26  5]
 [20 49 65 11 19 21  5 20 92 64]
 [91 42 50 39 72 83 85 10 84 76]
 [38 50 74 92 95 67 67 83 58 41]
 [40 65 20 65 77  2 66 59 12  6]
 [89 99 34 25  2 17 31  6 87 86]
 [21 86 12  1 41 73 63 15  4 59]
 [72 71 35 70 58 91 96  5 40 59]
 [16 15 47 88 66 68 53 26 24 31]]
